### ISSUE TITLE
Android 5.1 error

### ISSUE THREAD

**Issue by appukrb** [douglasspgyn/CircularCountdown#11]
In Android 5.1 I am getting following error

`  Caused by: java.lang.ClassCastException: androidx.core.graphics.drawable.WrappedDrawableApi21 cannot be cast to android.graphics.drawable.LayerDrawable
        at douglasspgyn.com.github.circularcountdown.CircularCountdown.setProgressForegroundColor(CircularCountdown.kt:237)
        at douglasspgyn.com.github.circularcountdown.CircularCountdown.updateStyle(CircularCountdown.kt:95)
        at douglasspgyn.com.github.circularcountdown.CircularCountdown.<init>(CircularCountdown.kt:30)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:378) 
        at android.app.Dialog.setContentView(Dialog.java:490) 
        at com.oss.pos.activity.LoginActivity.enterOTPDialog(LoginActivity.java:663) 
        at com.oss.pos.activity.LoginActivity$1.onResponse(LoginActivity.java:386) 
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:71) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) `

**Comment by douglas-srs** [comment]
Did you override the circular_progress.xml drawable file?

I stumbled upon the same issue, I tried replacing it with a RotateDrawable but the library is typecasting it to LayerDrawable on https://github.com/douglasspgyn/CircularCountdown/blob/78ed52613973cf4f597e82da12a8944ff524c8d5/app/src/main/java/douglasspgyn/com/github/circularcountdown/CircularCountdown.kt#L237 and https://github.com/douglasspgyn/CircularCountdown/blob/78ed52613973cf4f597e82da12a8944ff524c8d5/app/src/main/java/douglasspgyn/com/github/circularcountdown/CircularCountdown.kt#L251
