### ISSUE TITLE
Crashes on API 19 : ClassCastException: android.support.v4.graphics.drawable.WrappedDrawableApi19 cannot be cast to android.graphics.drawable.LayerDrawable ClassCastException

### ISSUE THREAD

**Issue by TheGabCode** [douglasspgyn/CircularCountdown#9]
I plan to use the CircularCountdown from API 19 - 27, so far I have only tested it in API 24 and 27 and there are no problems. But somehow I tried using API 19 and the app crashes when I change to a view/ set to a view using the CircularCountdown.

I think it has something to do with `ClassCastException: android.support.v4.graphics.drawable.WrappedDrawableApi19 cannot be cast to android.graphics.drawable.LayerDrawable`

here's the whole error in the log
 
`Process: com.name.appname PID: 3761
                                                                       android.view.InflateException: Binary XML file line #0: Error inflating class douglasspgyn.com.github.circularcountdown.CircularCountdown
                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:621)
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697)
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:756)
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                           at com.app.appname.fragments.ViewProductFragment.onCreateView(ViewProductFragment.kt:62)
                                                                           at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
                                                                           at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
                                                                           at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
                                                                           at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
                                                                           at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
                                                                           at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
                                                                           at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
                                                                           at android.os.Handler.handleCallback(Handler.java:733)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:136)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                           at dalvik.system.NativeStart.main(Native Method)
                                                                        Caused by: java.lang.reflect.InvocationTargetException
                                                                           at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                           at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:595)
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:756) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:759) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:759) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                           at com.app.appname.fragments.ViewProductFragment.onCreateView(ViewProductFragment.kt:62) 
                                                                           at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346) 
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428) 
                                                                           at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759) 
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827) 
                                                                           at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797) 
                                                                           at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596) 
                                                                           at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383) 
                                                                           at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338) 
                                                                           at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245) 
                                                                           at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703) 
                                                                           at android.os.Handler.handleCallback(Handler.java:733) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                           at android.os.Looper.loop(Looper.java:136) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                           at dalvik.system.NativeStart.main(Native Method) 
                                                                        Caused by: java.lang.ClassCastException: android.support.v4.graphics.drawable.WrappedDrawableApi19 cannot be cast to android.graphics.drawable.LayerDrawable
                                                                           at douglasspgyn.com.github.circularcountdown.CircularCountdown.setProgressForegroundColor(CircularCountdown.kt:237)
                                                                           at douglasspgyn.com.github.circularcountdown.CircularCountdown.updateStyle(CircularCountdown.kt:95)
                                                                           at douglasspgyn.com.github.circularcountdown.CircularCountdown.<init>(CircularCountdown.kt:30)
                                                                           at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                           at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:595) 
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:756) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:759) 
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:759) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                           at com.app.appname.fragments.ViewProductFragment.onCreateView(ViewProductFragment.kt:62) 
                                                                           at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346) 
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428) 
                                                                           at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759) 
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827) 
                                                                           at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797) 
                                                                           at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596) 
                                                                           at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383) 
                                                                           at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338) 
                                                                           at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245) 
                                                                           at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703) 
                                                                           at android.os.Handler.handleCallback(Handler.java:733) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                           at android.os.Looper.loop(Looper.java:136) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                           at dalvik.system.NativeStart.main(Native Method) `

Is this a problem in the library or something fixable by myself? Thank you.

**Comment by TheGabCode** [comment]
@douglasspgyn

**Comment by davingss** [comment]
> I plan to use the CircularCountdown from API 19 - 27, so far I have only tested it in API 24 and 27 and there are no problems. But somehow I tried using API 19 and the app crashes when I change to a view/ set to a view using the CircularCountdown.
> 
> I think it has something to do with `ClassCastException: android.support.v4.graphics.drawable.WrappedDrawableApi19 cannot be cast to android.graphics.drawable.LayerDrawable`
> 
> here's the whole error in the log
> 
> `Process: com.name.appname PID: 3761 android.view.InflateException: Binary XML file line #0: Error inflating class douglasspgyn.com.github.circularcountdown.CircularCountdown at android.view.LayoutInflater.createView(LayoutInflater.java:621) at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697) at android.view.LayoutInflater.rInflate(LayoutInflater.java:756) at android.view.LayoutInflater.rInflate(LayoutInflater.java:759) at android.view.LayoutInflater.rInflate(LayoutInflater.java:759) at android.view.LayoutInflater.inflate(LayoutInflater.java:492) at android.view.LayoutInflater.inflate(LayoutInflater.java:397) at com.app.appname.fragments.ViewProductFragment.onCreateView(ViewProductFragment.kt:62) at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346) at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428) at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759) at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827) at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797) at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596) at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383) at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338) at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245) at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703) at android.os.Handler.handleCallback(Handler.java:733) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:136) at android.app.ActivityThread.main(ActivityThread.java:5017) at java.lang.reflect.Method.invokeNative(Native Method) at java.lang.reflect.Method.invoke(Method.java:515) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) at dalvik.system.NativeStart.main(Native Method) Caused by: java.lang.reflect.InvocationTargetException at java.lang.reflect.Constructor.constructNative(Native Method) at java.lang.reflect.Constructor.newInstance(Constructor.java:423) at android.view.LayoutInflater.createView(LayoutInflater.java:595) at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697)  at android.view.LayoutInflater.rInflate(LayoutInflater.java:756)  at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)  at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)  at android.view.LayoutInflater.inflate(LayoutInflater.java:492)  at android.view.LayoutInflater.inflate(LayoutInflater.java:397)  at com.app.appname.fragments.ViewProductFragment.onCreateView(ViewProductFragment.kt:62)  at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)  at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)  at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)  at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)  at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)  at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)  at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)  at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)  at android.os.Handler.handleCallback(Handler.java:733)  at android.os.Handler.dispatchMessage(Handler.java:95)  at android.os.Looper.loop(Looper.java:136)  at android.app.ActivityThread.main(ActivityThread.java:5017)  at java.lang.reflect.Method.invokeNative(Native Method)  at java.lang.reflect.Method.invoke(Method.java:515)  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)  at dalvik.system.NativeStart.main(Native Method)  Caused by: java.lang.ClassCastException: android.support.v4.graphics.drawable.WrappedDrawableApi19 cannot be cast to android.graphics.drawable.LayerDrawable at douglasspgyn.com.github.circularcountdown.CircularCountdown.setProgressForegroundColor(CircularCountdown.kt:237) at douglasspgyn.com.github.circularcountdown.CircularCountdown.updateStyle(CircularCountdown.kt:95) at douglasspgyn.com.github.circularcountdown.CircularCountdown.<init>(CircularCountdown.kt:30) at java.lang.reflect.Constructor.constructNative(Native Method)  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)  at android.view.LayoutInflater.createView(LayoutInflater.java:595)  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697)  at android.view.LayoutInflater.rInflate(LayoutInflater.java:756)  at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)  at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)  at android.view.LayoutInflater.inflate(LayoutInflater.java:492)  at android.view.LayoutInflater.inflate(LayoutInflater.java:397)  at com.app.appname.fragments.ViewProductFragment.onCreateView(ViewProductFragment.kt:62)  at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)  at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)  at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)  at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)  at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)  at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)  at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)  at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)  at android.os.Handler.handleCallback(Handler.java:733)  at android.os.Handler.dispatchMessage(Handler.java:95)  at android.os.Looper.loop(Looper.java:136)  at android.app.ActivityThread.main(ActivityThread.java:5017)  at java.lang.reflect.Method.invokeNative(Native Method)  at java.lang.reflect.Method.invoke(Method.java:515)  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)  at dalvik.system.NativeStart.main(Native Method) `
> 
> Is this a problem in the library or something fixable by myself? Thank you.

Same Error
